repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: uv run -- pytest -v
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #       always_run: true
  #       stages: [pre-push]
