# Production values for Watcher
# This file contains production-specific configuration

# Production replica count
replicaCount: 3

# Autoscaling configuration
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Production image settings
image:
  repository: your-registry/watcher
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

# Service configuration
service:
  type: LoadBalancer
  port: 8000
  targetPort: 8000

# Health check probes
livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Resource limits
resources:
  limits:
    cpu: 4000m
    memory: 8Gi
  requests:
    cpu: 2000m
    memory: 4Gi

# Production environment configuration
watcher:
  envState: "prod"
  
  # Database configuration for production
  database:
    url: "postgresql+asyncpg://watcher:${DB_PASSWORD}@${DB_HOST}:5432/watcher"
  
  # Redis configuration for production
  redis:
    url: "redis://${REDIS_HOST}:6379/1"
  
  # Production monitoring
  logfire:
    token: "${LOGFIRE_TOKEN}"
    console: "false"
  
  # Production notifications
  slack:
    webhookUrl: "${SLACK_WEBHOOK_URL}"
  
  # Production features (using watcher-prefixed versions below)
  
  # Watcher feature flags for production
  watcherAutoCreateAnomalyDetectionRules: "true"
  watcherProfilingEnabled: "false"
  watcherTimelinessCheckLookbackMinutes: "60"
  watcherTimelinessCheckSchedule: "*/15 * * * *"
  watcherFreshnessCheckSchedule: "0 * * * *"
  watcherCeleryQueueHealthCheckSchedule: "*/5 * * * *"

# Celery worker configuration for production
celery:
  replicaCount: 2
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  # Autoscaling for Celery workers
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 8
    targetCPUUtilizationPercentage: 70
  # Celery Beat configuration for production
  beat:
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi

# Service configuration for production (external access)
service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

# Resource limits for production
resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 2Gi

# Enable autoscaling in production
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

# No ingress needed - using LoadBalancer for external access
ingress:
  enabled: false

# Security context for production
podSecurityContext:
  fsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
