apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "watcher.fullname" . }}-celery-beat
  labels:
    {{- include "watcher.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "watcher.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: celery-beat
  template:
    metadata:
      labels:
        {{- include "watcher.labels" . | nindent 8 }}
        app.kubernetes.io/component: celery-beat
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: celery-beat
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            runAsNonRoot: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["uv", "run", "--", "celery", "-A", "src.celery_app", "beat", "--loglevel=info"]
          env:
            - name: UV_CACHE_DIR
              value: "/tmp/uv-cache"
          envFrom:
            - configMapRef:
                name: {{ include "watcher.fullname" . }}-config
            {{- if .Values.gcp.secretManager.enabled }}
            {{- range $key, $secret := .Values.gcp.secretManager.secrets }}
            - secretRef:
                name: {{ include "watcher.fullname" $ }}-{{ $key }}
            {{- end }}
            {{- end }}
          {{- with .Values.celery.beat.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
