{{- if .Values.gcp.secretManager.enabled }}
# GCP Secret Manager secrets using CSI driver
{{- range $key, $secret := .Values.gcp.secretManager.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "watcher.fullname" $ }}-{{ $key }}
  labels:
    {{- include "watcher.labels" $ | nindent 4 }}
  annotations:
    secret-manager.gcp.io/secret-name: "{{ $.Values.gcp.secretManager.projectId }}/{{ $secret.name }}"
    secret-manager.gcp.io/secret-version: "{{ $secret.version }}"
type: Opaque
data:
  {{ $key | upper }}: ""  # Will be populated by GCP Secret Manager CSI driver
{{- end }}
{{- end }}
