{{- if .Values.gcp.secretManager.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gcp.secretManager.serviceAccount.name }}
  labels:
    {{- include "watcher.labels" . | nindent 4 }}
  {{- with .Values.gcp.secretManager.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
